### ISSUE TITLE
how to prepare data and training this code?

### ISSUE THREAD

**Issue by kingback2019** [xieyuankun/TDL-ADD#1]
how to prepare data and training this code

**Comment by xieyuankun** [comment]
The general process is as follows: Extract the last hidden states of Wav2Vec2-XLS-R using preprocess.py and save them offline. Then, proceed to train using main_train.py. Change the label path to "label/xxx_real1_pad1.txt." Please note that you need to download the corresponding ASVspoof2019PS dataset and LAV-DF dataset yourself. 
I will update the details once the paper is accepted.

**Comment by kingback2019** [comment]
Thank you for your answer.
