### ISSUE TITLE
preprocess.py文件问题

### ISSUE THREAD

**Issue by Clychee7517** [xieyuankun/TDL-ADD#5]
你的preprocess.py文件会一次性把数据集导入cpu撑爆，请问是否有改进的代码？

**Comment by xieyuankun** [comment]
您好，我这个preprocess是实例化dataset后循环dataset，一个个提wav2vec，不知道您说的cpu撑爆是指的占用率100%吗，是因为实例化Wav2Vec2Mode的时候加载到cpu上了吗？我这边提离线特征一直是这套代码，除了每次遍历只有一条比较慢别的还好，也可以再加个dataloader遍历，不知道能否解决你说的撑爆问题。
