### ISSUE TITLE
训练问题

### ISSUE THREAD

**Issue by QZ-z** [xieyuankun/TDL-ADD#6]
您好，请问能否告知一下您训练的环境，我采用您开源的代码进行训练的时候，十分缓慢。如果可以，能否给出一个预训练模型，方便我进行一些测试。

**Comment by xieyuankun** [comment]
您可以尝试检查下以下几项：
1. dataloader 的 num_worker数量
2. GPU利用率，如果GPU利用率不高，那么就是读取速度不够，GPU大部分时间在等待数据，可以看下是否存在硬盘IO瓶颈，如果IO到瓶颈了，目前没有很好的解决方案，最有用的方法只能将特征放至固态硬盘或者扩大RAM。也可以尝试改成在线训练模式，但个人实测速度远不如离线训练。

TIP：由于数据是离线存在硬盘里，在第一个epoch时会读取到RAM中，从第二个epoch开始，如果你的RAM足够存放所有离线特征，那么训练速度将会很快，此时GPU利用率应该会拉满，如果GPU利用率没上去一般就是IO瓶颈了。如果用固态的话从第一个epoch开始GPU利用率就会非常稳定。

预训练模型因为一些客观原因暂时无法提供。

**Comment by QZ-z** [comment]
感谢您的解答！同时十分抱歉，我又产生了一些新的问题：
1. 在该库中，lr的设置为$10^{-4}$但论文中实验参数标识为$10^{-5}$，在训练的时候是以论文中值为标准么
2. 我注意到文章中做了不使用ESM模块的消融实验，请问消融实验的设置是否是不使用EmbeddingModule和对应的loss，仅使用主干中的卷积操作

**Comment by xieyuankun** [comment]
1. 以我目前鉴伪的经验应该是10^{-4}，即初始0.0001为好，但事实上LR、batchsize等超参取哪个应该差不了太多（只要数值不太偏激），决定因素最大的还是特征和主干网络。
2. 你理解的没错，文章中是将args.lam置为0仅用BCE的结果。
